version: '3.8'

services:
  app:
    build: .
    container_name: timenest_agent
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
    ports:
      - "5001:5001"
